### PR TITLE
Add Makefile

### PR DESCRIPTION
**Pull request by infinitymdm**
Added a Makefile. Please verify that this works by pulling my branch and executing the following:
- cd src
- make

After executing make, the console should show the build process without errors. Verify things are working by running main.

### CODE REVIEW

**Comment by Icosahunter** [comment]
Okay, I'll give it a shot

**Comment by Icosahunter** [comment]
Ok, it works but I had to manually make a bin folder, so you may want to add something to generate that folder if it's not present.

**Comment by infinitymdm** [comment]
> add something to generate that folder if it's not present.

I'll go ahead and do this.

**Comment by infinitymdm** [comment]
@Icosahunter I've made the requested changes. Check it out and if it works for you, go ahead and do the merge.

**Comment by Icosahunter** [comment]
looks like it works!

**Pull request merged**
